:sparkles: VNF-2193 Add mlb commands
nttcom/eclcli pull request #109
Opened 2022-11-15 03:55 UTC by yamashita-hiroto

Add the following mlb command

- certificate
- health-monitor
- listener
- load-balancer
- operation
- plan
- policy
- rute
- rule
- system-update
- tls-policy

2022-11-22 05:34 UTC, sugimo-s commented on eclcli/mlb/v1/mlb_load_balancer.py
> +            interfaces=parsed_args.interfaces,
```suggestion
            interfaces=interfaces,
```

2022-11-22 05:37 UTC, sugimo-s commented on eclcli/mlb/v1/mlb_load_balancer.py
> +            interfaces=parsed_args.interfaces,
parsed_argsはコマンドライン引数ですので、メンバーとして `interface` はあっても `interfaces` はありません。
195-205行目で `parsed_args.interface` から変数interfacesを作成しています。
ここに指定すべきは変数interfacesのようです。

2022-11-28 08:27 UTC, yamashita-hiroto commented on eclcli/mlb/v1/mlb_load_balancer.py
> +            interfaces=parsed_args.interfaces,
ご確認ありがとうございました
ご指摘の通り、`parsed_args` は記述ミスで不要でしたので削除しました

2022-11-29 04:31 UTC, NaoShark requested changes

2022-11-29 04:31 UTC, NaoShark commented on eclcli/mlb/client.py
> +from eclcli.common import utils
```suggestion
```
使用されていないようです。

2022-11-29 04:31 UTC, NaoShark commented on eclcli/mlb/v1/mlb_health_monitor.py
> +import base64
```suggestion
```
使用されていないようです。(listener や load_balancer についても当てはまるので展開をお願い致します。)

2022-11-29 06:29 UTC, yamashita-hiroto commented on eclcli/mlb/client.py
> +from eclcli.common import utils
ご確認ありがとうございます
削除しました

2022-11-29 06:30 UTC, yamashita-hiroto commented on eclcli/mlb/v1/mlb_health_monitor.py
> +import base64
ご確認ありがとうございます
各ファイルから未使用の `import base64` を削除しました

2022-11-30 01:11 UTC, NaoShark approved these changes

2022-11-30 02:06 UTC, sugimo-s approved these changes

2022-11-30 02:09 UTC, merged