Modified for removing parameters of updating vnas
nttcom/eclcli pull request #56
Opened 2018-11-08 07:29 UTC by kazunari-kamata

2018-11-09 06:05 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
>              default=[],
nargs='+' となっており、1つ以上のinterface引数を渡さないとエラーになるので、defaultオプションは不要ではないでしょうか？

2018-11-09 06:09 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        parser.add_argument(
今の実装だと、interface引数を2つ以上渡して、かつIDを渡さなかった場合に最後の引数をIDと解釈してリクエストを発行してしまいます。
typeオプションを使って引数がUUIDフォーマットに従っているかチェックすれば、このケースのバリデーションできると思います。

2018-11-09 06:11 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
>              default=[],
上のコメントと同様にdefaultオプションは不要ではないでしょうか？

2018-11-09 06:12 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        parser.add_argument(
interface updateでもコメントしましたが、typeオプションでUUIDかどうかのチェックをするのがベターだと思います。

2018-11-09 06:13 UTC, kazyshr requested changes
コメントしました。IDがUUIDフォーマットかどうかのバリデーションは必須ではありませんが、実装していただけると嬉しいです。

2018-11-09 06:56 UTC, kazunari-kamata commented on eclcli/vnf/v1/virtual_network_appliance.py
>              default=[],
interface引数無し(nargs='?'or'*')の場合、どのようになればよろしいでしょうか?
複数のinterface引数でのupdateが可能という前提(現状と同等)だったかと思い(1以上)としておりました。
※2つのupdate interfaceで下記エラーになってしまうので本修正を致しました。
ecl vna appliance interface update: error: unrecognized arguments: afdb6445-2141-43b0-b81a-a157d8e8db73

2018-11-09 06:57 UTC, kazunari-kamata commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        parser.add_argument(
こちら修正致します

2018-11-09 08:06 UTC, kazunari-kamata commented on eclcli/vnf/v1/virtual_network_appliance.py
>              default=[],
default=[],を無くす修正を致します

2018-11-09 08:07 UTC, kazunari-kamata commented on eclcli/vnf/v1/virtual_network_appliance.py
>              default=[],
default=[],を無くす修正を致します

2018-11-13 05:43 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        parser.add_argument(
ありがとうございます、修正を確認しました。

2018-11-13 05:49 UTC, kazyshr requested changes
変更ありがとうございます！
一点だけ表示するメッセージについてコメントしました。確認をお願いします。

2018-11-13 05:49 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        msg = _("You must specify uuid")
このメッセージだとどの引数に対するメッセージか不明瞭だと思うので、以下のように変更してみてはいかがでしょうか。
`msg = "%r is not a valid uuid"
raise exceptions.CommandError(msg % uuid)`

2018-11-13 06:42 UTC, kazunari-kamata commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        msg = _("You must specify uuid")
御提案頂きましたメッセージに修正致しました

2018-11-13 10:07 UTC, kazyshr commented on eclcli/vnf/v1/virtual_network_appliance.py
> +        msg = _("You must specify uuid")
ありがとうございます、確認しました。

2018-11-13 10:07 UTC, kazyshr commented
LGTMです。マージします。

2018-11-13 10:07 UTC, merged