fix param key of `update uefi` request body
nttcom/eclcli pull request #80
Opened 2020-04-28 06:37 UTC by hanasuke

resolve #79 

I fixed request body of `Update UEFI` for baremetal server.

before:
```
$ ecl --debug baremetal uefi update XXX --settings '{"SataSecureErase":{"value":"Enabled"}}'
START with options: ['--debug', 'baremetal', 'uefi', 'update', 'XXX', '--settings', '{"SataSecureErase":{"value":"Enabled"}}']
: (snip)
REQ: curl -g -i -X PUT https://baremetal-server-jp1-ecl.api.ntt.com/v2/tenant_id/servers/XXX/uefi -H "Accept: application/json" -H "X-Auth-Token: {SHA1}XXX" -H "User-Agent: python-bearclient" -H "Content-Type: application/json" -d '{"uefi": {"setting": {}, "settings": {"SataSecureErase": {"value": "Enabled"}}}}'
```

after:
```
$ ecl --debug baremetal uefi update XXX --settings '{"SataSecureErase":{"value":"Enabled"}}'
START with options: ['--debug', 'baremetal', 'uefi', 'update', 'XXX', '--settings', '{"SataSecureErase":{"value":"Enabled"}}']
: (snip)
REQ: curl -g -i -X PUT https://baremetal-server-jp1-ecl.api.ntt.com/v2/tenant_id/servers/XXX/uefi -H "Accept: application/json" -H "X-Auth-Token: {SHA1}XXX" -H "User-Agent: python-bearclient" -H "Content-Type: application/json" -d '{"uefi": {"setting": {"SataSecureErase": {"value": "Enabled"}}}}'
```

2020-04-28 09:18 UTC, kazyshr commented on eclcli/bare/v2/uefi.py
>          if parsed_args.settings:
```suggestion
        if parsed_args.setting:
```

2020-04-28 09:18 UTC, kazyshr commented on eclcli/bare/v2/uefi.py
> +            body['uefi']['setting'] = json.loads(parsed_args.settings)
```suggestion
            body['uefi']['setting'] = json.loads(parsed_args.setting)
```

2020-04-28 09:25 UTC, kazyshr requested changes
Thanks for the PR.
Can you rename all "settings" to "setting" over UpdateUEFI class including comments?

2020-04-28 13:48 UTC, hanasuke commented on eclcli/bare/v2/uefi.py
> +            body['uefi']['setting'] = json.loads(parsed_args.settings)
fixed

2020-04-28 13:48 UTC, hanasuke commented on eclcli/bare/v2/uefi.py
>          if parsed_args.settings:
fixed

2020-04-28 13:52 UTC, hanasuke commented
I renamed `parsed_args.settings` to `parsed_args.setting`.

I also added the `--setting` alias to the argument `--settings` .
`--settings` is maintained for consistency with official documentation and compatibility with older scripts.
ref: https://ecl.ntt.com/documents/tutorials/eclc/rsts/bare/uefi/update.html#id3

2020-04-28 13:59 UTC, hanasuke commented
This is execution logs.
* `ecl --debug baremetal uefi update server_id --settings '{"SataSecureErase":{"value":"Enabled"}}'`
```
: snip
REQ: curl -g -i -X PUT https://baremetal-server-jp1-ecl.api.ntt.com/v2/tenant_id/servers/server_id/uefi -H "Accept: application/json" -H "X-Auth-Token: {SHA1}XXX" -H "User-Agent: python-bearclient" -H "Content-Type: application/json" -d '{"uefi": {"setting": {"SataSecureErase": {"value": "Enabled"}}}}'
```
* `ecl --debug baremetal uefi update server_id --setting '{"SataSecureErase":{"value":"Disabled"}}'`
```
REQ: curl -g -i -X PUT https://baremetal-server-jp1-ecl.api.ntt.com/v2/tenant_id/servers/server_id/uefi -H "Accept: application/json" -H "X-Auth-Token: {SHA1}XXX" -H "User-Agent: python-bearclient" -H "Content-Type: application/json" -d '{"uefi": {"setting": {"SataSecureErase": {"value": "Disabled"}}}}'

```

2020-04-30 03:12 UTC, kazyshr approved these changes
LGTM 👍

2020-04-30 03:12 UTC, merged