remove rdb subcommand
nttcom/eclcli pull request #90
Opened 2021-05-31 12:16 UTC by hanasuke

I removed `ecl rdb` subcommands.

According to [service descriptions](https://ecl.ntt.com/documents/service-descriptions/), ECL2.0 doesn't have RDB menu.

before (v3.0.0):
```
$ ecl --help rdb
Command "rdb" matches:
  rdb database create
  rdb database delete
  rdb database list
  rdb datastore list
  rdb flavor list
  rdb instance create
  rdb instance delete
  rdb instance list
  rdb instance show
  rdb user create
  rdb user delete
  rdb user grant
  rdb user list
  rdb user revoke
  rdb user show
```

after(this patch):
```
$ ecl --help rdb       
Unknown command ['rdb']
```

2021-06-03 03:42 UTC, t-wata requested changes
Thanks for your PR.
I have commented on the line that should be removed.

I would also like to ask you to remove the following functions as well, because they are only used in “database" and are not very reusable.

https://github.com/nttcom/eclcli/blob/master/eclcli/common/utils.py#L93-L94
https://github.com/nttcom/eclcli/blob/master/eclcli/common/utils.py#L472-L493

2021-06-03 03:42 UTC, t-wata commented on setup.cfg
>  ecl.database.v1 =
Please delete this line as well.
```suggestion

```

2021-06-03 16:46 UTC, hanasuke commented
Thank you for your review!
I removed reviewed points additionally.

2021-06-03 23:39 UTC, NaoShark approved these changes

2021-06-04 00:31 UTC, t-wata approved these changes
LGTM 👍 Thank you for your contribution!

2021-06-04 00:31 UTC, merged