:sparkles: IF-6056 vna operation show command add request_body suppor…
nttcom/eclcli pull request #92
Opened 2021-08-16 09:38 UTC by Nishioka-Aiko

vna operation show コマンドのrequest_bodyが、それまではstringのみ対応でした。
その設定をjson objectにも対応するように修正しました。

2021-08-17 03:30 UTC, shimisho requested changes
PRありがとうございます。以下、コードに記載したコメント以外で気になったところです。
* WAに以下の記載があるので今後意識していただければと思います
> nttcom organization の OSS として公開しているリポジトリ（e.g. eclcli/eclsdk, terraform provider）については、PR のタイトル・説明は英語で記載し、PR の中で Reviewer とやり取りするコメントについては日本語で記載する。

* request_body が空の場合があるようですがこのケースの考慮はされてますでしょうか？

2021-08-17 03:30 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +        if type(data.request_body) is str :
PEP8違反があるので遵守するように修正してください。

2021-08-17 03:30 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +        elif type(data.request_body) is dict :
PEP8違反があるので遵守するように修正してください。

2021-08-17 03:30 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +        setattr(data, 'request_body', json.dumps(req_body_dict, indent=2))
`Local variable 'req_body_dict' be referenced before assignment` エラーの可能性があるので変数宣言を行うスコープを修正してください。

2021-08-17 03:30 UTC, shimisho commented on eclcli/vnf/v1/operation.py
>              req_body = data.request_body
この変数は宣言する必要があるのでしょうか？

2021-08-17 09:52 UTC, Nishioka-Aiko reviewed
IF-6056 fixed conditions

2021-08-17 10:29 UTC, shimisho requested changes

2021-08-17 10:29 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = data.request_body
すでにコメントしていることですが、この変数代入は必要なのでしょうか？ `setattr`関数のパラメータにそのまま入れているので不要に見えます。

2021-08-17 10:29 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +        elif data.request_body:
この分岐の書き方だと `data.request_body`がNullの時も下の処理が行われて `json.loads()` で TypeErrorになると思います。

2021-08-17 12:29 UTC, shimisho requested changes

2021-08-17 12:29 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = data.request_body
すでにコメントしていることですが、この変数代入は必要なのでしょうか？ `setattr()`のパラメータにそのまま入れているので不要に見えます。

2021-08-18 01:42 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +        if type(data.request_body) is str :
python PEP8違反を調べて修正しました。
新しいファイルをアップしなおしたので、ご確認ください。

2021-08-18 01:42 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +        elif type(data.request_body) is dict :
python PEP8違反を調べて修正しました。
新しいファイルをアップしなおしたので、ご確認ください。

2021-08-18 01:42 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
>              req_body = data.request_body
変数に代入部分を削除しました。

2021-08-18 01:42 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +        setattr(data, 'request_body', json.dumps(req_body_dict, indent=2))
値を代入するスコープを修正しました。

2021-08-18 03:12 UTC, Nishioka-Aiko reviewed
IF-6056  conditions fixed request_body = {}

2021-08-18 03:12 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = data.request_body
req_body_dictを使わず、data.request_bodyを使用する形式に修正したファイルをアップしました。

2021-08-20 05:42 UTC, shimisho requested changes

2021-08-20 05:42 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +                req_body_dict = json.loads(data.request_body)
Pythonは三項演算子を使うことで1行で変数代入の条件分岐を記述できます。
https://qiita.com/howmuch515/items/bf6d21f603d9736fb4a5

2021-08-20 07:32 UTC, shimisho requested changes

2021-08-20 07:32 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = {}
`req_body_dict` の値の代入は次の処理で行われていますがこの変数代入の意図はなんでしょうか？

2021-08-20 07:32 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = req_body if type(req_body) is dict else json.loads(req_body)
この記述でも問題ないように見えますが、改修前が
```
req_body_dict = json.loads(req_body)
```
なのでこれをベースに三項演算子を記述した方が変更内容が分かりやすいと思います。

2021-08-20 08:34 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +                req_body_dict = json.loads(data.request_body)
三項演算子をつかって下記のように書き換えたところ、json.loads(req_body)を入れるとsyntaxerrorが起きました。
            req_body = data.request_body
            req_body_dict = {}
            req_body_dict = req_body if type(req_body) is dict else json.loads(req_body)
実行上は問題ないようです。
使っているエディターはVSCodeで拡張機能でcornflakes-linterにflake8を設定しています。

2021-08-20 08:34 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
>              req_body = data.request_body
元の書き方に近づけたほうが良いかと思い、req_body = data.request_bodyを復活させましたが、
変数を使わない方式でも問題ないですね。
上記を削除して、変数に代入している三項演算子を下記に修正しました。
            req_body_dict = data.request_body if type(data.request_body) is dict else json.loads(data.request_body)

2021-08-20 08:34 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = {}
依然、if文でスコープの話が出たので、初期設定でそのままにしてありました。
ifとelseのみになったので、削除しても問題なくなったので、削除します。

2021-08-20 08:34 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = req_body if type(req_body) is dict else json.loads(req_body)
req_bodyを以前の記述data.request_bodyに修正します。

2021-08-20 09:29 UTC, shimisho requested changes

2021-08-20 09:29 UTC, shimisho commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = json.loads(data.request_body) if type(data.request_body) is str else data.request_body
data.request_body を変数にした方が可読性が良いと思います。

2021-08-20 09:37 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/operation.py
> +            req_body_dict = json.loads(data.request_body) if type(data.request_body) is str else data.request_body
修正前の変数を使用し、
req_body = data.request_body
req_body_dict = json.loads(req_body) if type(req_body) is str else req_body
のように修正いたします。

2021-08-20 09:53 UTC, shimisho approved these changes

2021-08-22 23:00 UTC, keiichi-hikita approved these changes

2021-08-23 02:04 UTC, merged