A nishioka IF-5581 vna create fix no interface 1 8 slot
nttcom/eclcli pull request #95
Opened 2021-09-09 02:17 UTC by Nishioka-Aiko

:recycle: IF-5581 vna appliance create fixed no interface and  multiple 1 to 8 slot-no

2021-09-12 23:50 UTC, NaoShark requested changes
`UpdateVirtualNetworkApplianceInterfaces` にも同様の内容の適用をお願いします。

2021-09-12 23:50 UTC, NaoShark commented on eclcli/vnf/v1/virtual_network_appliance.py
> +                    msg = _("slot-no is none")
```suggestion
                    msg = _("slot-no is not specified")
```

2021-09-12 23:50 UTC, NaoShark commented on eclcli/vnf/v1/virtual_network_appliance.py
> +                if len(slot_no) != 1 or not slot_no.isdigit() or int(slot_no) > 8 or int(slot_no) < 1:
```suggestion
                if not slot_no.isdigit() or int(slot_no) > 8 or int(slot_no) < 1:
```
該当部分は必要でしょうか？

2021-09-13 01:03 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/virtual_network_appliance.py
> +                if len(slot_no) != 1 or not slot_no.isdigit() or int(slot_no) > 8 or int(slot_no) < 1:
slot-no=06と指定すると、該当部分がないとエラーをスキップしてしまい、
外部でエラー「HttpException: Invalid virtual_network_appliance.interfaces.interface_06」
が表示されるようになってしまいました。
そのため、該当部分もあったほうが、処理内でslot-noのエラーをチェックできると思います。

2021-09-13 08:01 UTC, ysssasaki requested changes

2021-09-13 08:01 UTC, ysssasaki commented on eclcli/vnf/v1/virtual_network_appliance.py
> +            msg = _("You can specify 1 to 8 interface in virtual network "
```suggestion
        elif len(parsed_args.interface) > 8:
            msg = _("You can specify 0 to 8 interface in virtual network "
```
個数は0でもOKかと思います

2021-09-13 08:01 UTC, ysssasaki commented on eclcli/vnf/v1/virtual_network_appliance.py
> +                if len(slot_no) != 1 or not slot_no.isdigit() or int(slot_no) > 8 or int(slot_no) < 1:
slot-no=06など、0埋めされた場合をエラーにしたい場合は、そのケースを明確に判定出来る条件式にしたほうが良いかと思います。（その方が後でコードを見た人が分かりやすいので）
今回であれば1桁であることが悪いような条件式となっていますが、0埋めされているか否かを判定して下さい。
今はvSRXでinterfaceは8個しか作れませんが、今後2桁（例えば16個など）になった場合でもそのまま使える書き方が良いです。

また別の方針として、0埋めされた数字をECLCLI側で0を消してあげて、リソースを作ってしまうという考え方もあるかと思います。
slot-no=06と入力されればinterface_6を作成する、という意味です。

2021-09-13 08:35 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/virtual_network_appliance.py
> +            msg = _("You can specify 1 to 8 interface in virtual network "
--interfaceオプションがない場合は0ですね。
コメントありがとうございます。

2021-09-13 08:37 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/virtual_network_appliance.py
> +                if len(slot_no) != 1 or not slot_no.isdigit() or int(slot_no) > 8 or int(slot_no) < 1:
コメントありがとうございます。
「slot-no=06と入力されればinterface_6」
の方針に修正いたします。

2021-09-14 08:47 UTC, ysssasaki requested changes
この実装だとslot_no=6とslot_no=06を書かれたときに重複排除出来ずエラーになると思うのですが、いかがでしょう。

2021-09-14 09:46 UTC, Nishioka-Aiko commented
「この実装だとslot_no=6とslot_no=06を書かれたときに重複排除出来ずエラーになると思うのですが、いかがでしょう。」
ご指摘ありがとうございます。
slot-noの重複チェックを行う処理を追加します。

2021-09-16 09:17 UTC, ysssasaki requested changes

2021-09-16 09:17 UTC, ysssasaki commented on eclcli/vnf/v1/virtual_network_appliance.py
> +            # conflict interfaces
細かくてすみません、このコメントは削除いただいてよろしいでしょうか。

2021-09-16 09:17 UTC, ysssasaki commented on eclcli/vnf/v1/virtual_network_appliance.py
>          # conflict interfaces
こちらも削除お願いします

2021-09-16 09:45 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/virtual_network_appliance.py
> +            # conflict interfaces
承知しました。
削除いたします。

2021-09-16 09:46 UTC, Nishioka-Aiko commented on eclcli/vnf/v1/virtual_network_appliance.py
>          # conflict interfaces
承知しました。
削除いたします。

2021-09-17 04:05 UTC, ysssasaki approved these changes
LGTM 🍊

2021-09-17 10:03 UTC, NaoShark approved these changes
LGTM

2021-09-21 00:54 UTC, merged